### ISSUE TITLE
Unable to install

### ISSUE THREAD

**Issue by mudrd8mz** [Edunao/moodle-mod_masks#1]
The upgrade function `fix_id_field()` has three serious problem.

1. It has hard-coded `mdl_` prefix for tables so it can't work well on sites using different prefixes.
2. It uses MySQL specific SQL so it does not work on any other database for not good reason.
3. It should not exist as steps like this should be executed via XMLDB API only and the code snippets that XMLDB editor generates.

Actually, the point 3. applies to all other functions in the upgradelib.php.

**Comment by mudrd8mz** [comment]
Attempting to install the module on postgresql machine:

![image](https://cloud.githubusercontent.com/assets/85831/21191308/ff170588-c224-11e6-91bc-509afef9ea5d.png)

**Comment by Edunao** [comment]
Thank you for the bug report.
We had tested on postgresql - I'm not sure why it passed for us and failed for you but we will fix it.
I have re-checked the xmldb api. As far as I am aware the only way of adding a new table in an upgrade is with the kind of approach that I have used here. Have I got that wrong?
I had a first version of the plugin running with a smaller set of tables. When I came to add a new table I had trouble setting up its primary key. I'd appreciate pointers for how to do it 'the right way'.

**Comment by Edunao** [comment]
1. The hard coded mdl_ prefix has been fixed
2. The issue related to the quotes in the query. They have been removed and the install passed on a postgresql install.
3. I have re-read the xmldb documentation and I don't see what the correct method is for adding a new table in an upgrade step. The routine that we are discussing here was added to solve a problem that I encountered creating an auto-incremented primary key for a table. My attempts to achieve the same result via the xmldb API had failed.

**Comment by mudrd8mz** [comment]
> I don't see what the correct method is for adding a new table in an upgrade step

It is a common procedure done frequently in both plugins and in the moodle core itself. The point is that

1. The new table is described via the XMLDB and saved into the db/install.xml so that new installations start with the table already created
2. An upgrade step is implemented in the db/upgrade.php so that existing installations can be upgraded and have the table added. The inbuilt XMLDB editor generates the required PHP code for the upgrade for you (PHP code > add table).

As an example, look at how the new table `enrol_lti_tool_consumer_map` was added in https://github.com/moodle/moodle/commit/6092bbc07acfe8d5c9067482efc431b7cbabd7d1 into both install.xml and upgrade.php

The essential part to understand is that new installations should use db/install.xml only and upgrades should use db/upgrade.php only, and both ways should end up with the same DB structure.

**Comment by Edunao** [comment]
For some reason I wasn't notified of your post here so I missed it at the time of writing.
Anyhow, it is very clear. Many thanks.
