### ISSUE TITLE
Dependency on pdf2svg should be part of the module description

### ISSUE THREAD

**Issue by mudrd8mz** [Edunao/moodle-mod_masks#2]
There is no mention of the `pdf2svg` at https://moodle.org/plugins/mod_masks

All additional requirements like this should be explicitly documented and described. That is what the plugin description field is for.

**Comment by Edunao** [comment]
DEPENDENCIES added to description

**Comment by k-holland** [comment]
The pdf2svg dependancy should be also added to version.php as $plugin->dependencies, as explained in https://docs.moodle.org/dev/version.php

**Comment by mudrd8mz** [comment]
No. The `$plugin->dependencies` is for declaring a dependency on another Moodle plugin. This is a dependency on an executable binary being available on the server (similar to unoconv, gs, du and other utilities that Moodle makes use of). There is no support for declaring a dependency on such external programs in the code itself.
