### ISSUE TITLE
The rant in install.xml

### ISSUE THREAD

**Issue by mudrd8mz** [Edunao/moodle-mod_masks#3]
As explained in the RANT in db/install.xml, the file is not maintained any more. That is not acceptable. The file must describe the up-to-date schema of all the tables owned by the plugin. There are parts in the Moodle core code that rely on it.

The db/upgrade.php is there only for what the name suggests - upgrades of the database scheme from one version to another.

https://docs.moodle.org/dev/XMLDB_Documentation

**Comment by Edunao** [comment]
The change has been made.
