### ISSUE TITLE
Direct access to the raw user input and re-use of it on the rendered page

### ISSUE THREAD

**Issue by mudrd8mz** [Edunao/moodle-mod_masks#4]
The custom code uses direct access to the raw user input via superglobals like $_GET. There is a path in the code how the raw user input can get through the form_writer back to a screen - for example via the `lookupRefData()` in `addTextArea()`.

This is a serious and instant security risk (especially as there seems to be no CSRF protection).

**Comment by Edunao** [comment]
Fixed
