### ISSUE TITLE
Error reported on successful upload

### ISSUE THREAD

**Issue by mudrd8mz** [Edunao/moodle-mod_masks#6]
After uploading a PDF, I get an error message:

![image](https://cloud.githubusercontent.com/assets/85831/23710564/75528094-041d-11e7-854e-7c204b42afca.png)

* Note in the background, the notice says the document has been uploaded.
* After reloading, i can see the uploaded PDF
* There seems to be no way to scroll down the error message (also this whole UI widget looks really not-natural in Moodle).

**Comment by Edunao** [comment]
This issue only occured when debugging output was enabled. We have fixed it.
We have also added a scroll bar.
thank you
